### ISSUE TITLE
Pre-pulling the wrong cloudant image

### ISSUE THREAD

**Issue by khahmed** [IBM/deploy-ibm-cloud-private#11]
When we pre-pull images the cloudant image in the Vagrantfile is:
echo "Pulling #{image_repo}/icp-cloudantdb:#{version}..."
docker pull #{image_repo}/cloudantdb:#{version} &> /dev/null

However this is the image the installer actually pulls:
ibmcom/icp-datastore              2.1.0-beta-3        ebe697aa6df8        5 days ago          1.69GB

**Comment by tpouyer** [comment]
ah, they changed the name of the cloudantdb image.  Thanks I will update the Vagrant file with the correct name.

**Comment by tpouyer** [comment]
Fixed with PR #13
