### ISSUE TITLE
Install fail with ibmcom/iam-token-service - TASK [auth-config : IAM | Register a new Service Id]

### ISSUE THREAD

**Issue by kwinbur** [IBM/deploy-ibm-cloud-private#111]
Hi,

I have an install issue with my ICP 2.1.0.2 install. I have 1 master, 3 workers, and 1 proxy (all Ubuntu 16.04) running on a single ESXi 6.0 host and running into a failure at the "TASK [auth-config : IAM | Register a new Service Id]" Step.

**Comment by alansbb** [comment]
I have similar issue, failed with  "msg": "Status code was not [201]: Request failed: <urlopen error [Errno 111] Connection refused>".

Appreciated anyone can shed light on this please?

**Comment by kwinbur** [comment]
I think I am having a resource issue. The ICP install could be taking up so much CPU, RAM, Disk that the 10 retries might be too little of tries or I need to move my boot node away from the master node.

**Comment by alansbb** [comment]
Thanks and I guess the HW requirements is really important to ICP 2.1+.

I finally find out my issue is CPU SSE4.2 related,  basically my IBM server is too old which the Intel CPU not support SSE4.2, the icp_router ended up with instruct error. Check lscpu on ubuntu able to find it out.

I did the same installation on a newer server, problem gone.

**Comment by kwinbur** [comment]
You seem to be right @alansbb . I was able to get a single node installation on one of my laptops with an i7 processor. My older server only supports up to SSE3. 
I wonder if it's a requirement for only the boot node or maybe the master node too. Going to try an install with the boot node on a newer processor and the rest of the nodes on the older server.

**Comment by kwinbur** [comment]
I was able to do a successful install with the master and boot node on the SSE4.2 compatible server and the worker and proxy nodes on the server that can only support up to SSE3.

Main issue was running a master node on a server that could not support SSE4.2.
