### ISSUE TITLE
"icp: Creating worker1" -> "icp: Error: Failed container creation: Failed to load raw.lxc"

### ISSUE THREAD

**Issue by anbie** [IBM/deploy-ibm-cloud-private#126]
I'm trying to install ICP on my Mac. After installing latest versions of VirtualBox and Vagrant I kick off "vagrant up". After a while it stops while creating "worker1". 

Some more info from the console:
>>
Retrieving image: rootfs: 99% (20.10MB/s)
Retrieving image: rootfs: 100% (20.07MB/s)
Retrieving image: rootfs: 100% (20.06MB/s)
Retrieving image: rootfs: 100% (20.06MB/s)

    icp: Error: Failed container creation: Failed to load raw.lxc
    icp: Creating worker2
    icp:
    icp: Error: Failed container creation: Failed to load raw.lxc
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
<<

**Comment by jstzsyf** [comment]
I just hit the same problem as well.

**Comment by jstzsyf** [comment]
I fixed the problem by replacing “lxc.aa_profile” with “lxc.apparmor.profile” in Vagrantfile. You need to do “vagrant destroy” and then “vagrant up”.

**Comment by anbie** [comment]
Looks like there are changed configuration keys in the version of lxc that is being used (lxc info shows driver version 3.0.1). The updated table of keys can be found here: https://discuss.linuxcontainers.org/t/lxc-2-1-has-been-released/487..

Changing key “lxc.aa_profile” to  “lxc.apparmor.profile” in Vagrantfile does the trick.

**Comment by xpagesbeast** [comment]
I ran into this problem today... when I edited the file, and ran a vagrant destroy then up, I get 

```
=> icp: Running provisioner: shell...
   icp: Running: script: boot_lxd_worker_nodes
   icp: If this is your first time running LXD on this machine, you should also run: lxd init
   icp: To start your first container, try: lxc launch ubuntu:16.04
   icp: Creating worker1
   icp:
   icp: Error: Failed container creation: No storage pool found. Please create a new storage pool.
   icp: Creating worker2
   icp:
   icp: Error: Failed container creation: No storage pool found. Please create a new storage pool.
```

**Comment by tpouyer** [comment]
this issue has been resolved in the latest commit.
