### ISSUE TITLE
ICP 2.1.0.3 Vagrant Up - calico-node-xxxx pods CrashLoopBackOff

### ISSUE THREAD

**Issue by dieterkoenig** [IBM/deploy-ibm-cloud-private#131]
My Vagrantfile for an ICP 2.1.0.3 ran successfully, however, the final ensure_services_up step reports two calico-node-xxxxx pods on the worker nodes in a repeated CrashLoopBackOff loop. 

The ICP Console shows a suspicious event for the failed calico-node-xxxxx pods right before the next restart attempt: 
Warning | kubelet 192.168.27.101 | 2 | Failed | Error: failed to start container "calico-node": Error response from daemon: linux mounts: path /var/run/calico is mounted on /run but it is not a shared or slave mount

Has anyone observed this before and a clue what I can do about it?

**Comment by dieterkoenig** [comment]
Resolved with Vagrantfile updated for 2.1.0.3 - see https://github.com/IBM/deploy-ibm-cloud-private/blob/master/Vagrantfile - thanks

**Comment by dieterkoenig** [comment]
Reopened as the abovementioned problem STILL occurs with the latest Vagrantfile

**Comment by tpouyer** [comment]
Sorry missed this in my last commit.  There still seems to be an issue with the prometheus node exporter pods in the two worker nodes, I'll have to look into that.

https://github.com/IBM/deploy-ibm-cloud-private/issues/131

**Comment by dieterkoenig** [comment]
👍 Many thanks for the update - `vagrant up` now completes successfully with all services in running state. Moreover, after `vagrant suspend` + `vagrant resume`, everything continues to be fine, so I can resume my original work now.

🔺 Please note: the original problem (calico-node-xxxxx in CrashLoopBackOff with `path /var/run/calico is mounted on /run but it is not a shared or slave mount`) **IS BACK AGAIN** after `vagrant halt` + `vagrant up`, so you may want to revisit which path is executed in this scenario.
