### ISSUE TITLE
Catalog empty ICP 2.1.0.3

### ISSUE THREAD

**Issue by jphernandez1587** [IBM/deploy-ibm-cloud-private#135]
Hi,

I just made a fresh install with the latests Vagrant file, that installs ICP 2.1.0.3, on Mac 10.12, VirtualBox 5.2.12. However, the Catalog page shows no charts to install. The helm-api log file shows the following error:

Error from server (BadRequest): a container name must be specified for pod helm-api-7d6ff49b8c-sgb8g, choose one of: [rudder helmapi]

I've used previous Vagrant files for ICP installations and haven't had any issue like this before. Any idea what could be wrong or how can this error be solved?

Kind regards

**Comment by jphernandez1587** [comment]
Hi Steve,

Thanks for your reply! My vagrant machine could ping raw.githubusercontent.com, but not https://raw.githubusercontent.com , so I added it to /etc/hosts. I restarted the helm-api pod after adding it, also did a vagrant suspend/vagrant up, but still the Catalog page shows nothing. Any other suggestion?

**Comment by stevemart** [comment]
@jphernandez1587 i don't have any other suggestions, I'm not a maintainer, just passing by and saw your post had the same issues I ran into yesterday. Maybe @tpouyer can shed some light on it.

**Comment by tpouyer** [comment]
Turns out that it was the virtualbox dns proxy host resolver that was causing dns lookups to take too long.  Turning off the dns proxy in virtualbox resolves the issue.  

Please verify the latest changes resolve the problem for you and close the issue.

**Comment by jphernandez1587** [comment]
Thanks @tpouyer . As a workaround, it also worked for me to edit in my Vagrant machine the /etc/resolv.conf file and comment the nameserver line that had my master IP address and adding the following lines:

nameserver 8.8.8.8
nameserver 4.2.2.2

Afterwards, I restarted the dns-kube pod and the Catalog successfully showed the Helm Charts
