### ISSUE TITLE
Connecting to docker repo in local ICP 

### ISSUE THREAD

**Issue by kriston13** [IBM/deploy-ibm-cloud-private#137]
Hi,

I'm attempting to follow the instructions [here](https://www.ibm.com/support/knowledgecenter/en/SSBS6K_2.1.0.3/manage_images/configuring_docker_cli.html) to setup access to the ICP docker repo on my local ICP install.

```
$ scp vagrant@mycluster.icp:/etc/docker/certs.d/mycluster.icp:8500/ca.crt .
vagrant@mycluster.icp's password: 
scp: /etc/docker/certs.d/mycluster.icp:8500/ca.crt: Permission denied
```

Note that I'm using the `vagrant` user...

However, when I'm attempting to`scp` the file, I get an authentication error. Taking a look in the master node using `vagrant ssh`, I can see that the `/etc/docker` folder is actually set to 
```
drwx------ 3 root root    4096 Jul 30 01:44 docker
```
So attempting to use the `vagrant` user doesn't work for the `scp`.

And since I can't figure out what the `root` account's password is... I can't change the folder permissions either.

Can anybody provide either:
- a way to get ICP's docker repo's cert, OR
- the `admin` password for the locally installed ICP?

Thank you

**Comment by tpouyer** [comment]
as the vagrant user you can use “sudo” to elevate your permissions to root level without a password.

**Comment by kriston13** [comment]
@tpouyer, that... never occurred to me. It did work, thanks! :D

That said, SHOULD that folder be a root user only?

**Comment by tpouyer** [comment]
@kriston13 Installer sets the permissions on that folder.  The objective is to protect the certs which is understandable.  Typically an admin would setup ICP and hand out certs as needed.

**Comment by kriston13** [comment]
Hi @tpouyer. Thank you for the info, both a way forwards as well as the rationale. Cheers!
