### ISSUE TITLE
Intermittent hang/timeout during LXC container creation

### ISSUE THREAD

**Issue by pdfruth** [IBM/deploy-ibm-cloud-private#150]
When running '**vagrant up**' on a Macbook Pro, I've intermittently encountered the error message;

`Failed to assign IP to lxc nodes...`
`You may need to change the 'base_segment' value in the 'Vagrantfile' to another subnet like '192.168.56'.`

I've lxc exec'd into the lxc containers after encountering this error, and found that at least one of the containers has not completed it's initialization tasks.  And it seems to have more to do with container initialization than it does with network address conflicts.
It seems there is some sort of race/hang condition during lxc container creation.

I've recreated this several times.

After changing the **boot_lxd_worker_nodes** section of the Vagrantfile from this;

`boot_lxd_worker_nodes = <<SCRIPT`
`lxc launch -p default -p worker1 ubuntu:16.04 worker1`
`lxc launch -p default -p worker2 ubuntu:16.04 worker2`
`SCRIPT`

to this;

`boot_lxd_worker_nodes = <<SCRIPT`
`lxc init ubuntu:16.04 -p default -p worker1 worker1`
`lxc init ubuntu:16.04 -p default -p worker2 worker2`
`lxc start worker1`
`sleep 5`
`lxc start worker2`
`SCRIPT`

I no longer encounter the error.

**Comment by tpouyer** [comment]
thx, I'll see about pulling this syntax for starting the lxc containers into the Vagrantfile
