### ISSUE TITLE
disabled_management_services quote characters don't work with latest ICP

### ISSUE THREAD

**Issue by khahmed** [IBM/deploy-ibm-cloud-private#17]
The latest daily build of ICP with this Vagrantfile deploys the VA. It seems that the quote characters are incorrect and cause the the newest installer to think VA needs to be deployed:

disabled_management_services = '[“va”]'

should be:

disabled_management_services = '["va"]'

See Issue #2927 in IBM private cloud repo.

**Comment by tpouyer** [comment]
Fixed with PR #18
