### ISSUE TITLE
Helm install problems

### ISSUE THREAD

**Issue by doormat18** [IBM/deploy-ibm-cloud-private#170]
Just installed on my laptop with VBox. Noticed a few things wrong.

1. For whatever reason, HELM_HOME=/usr/local/bin/helm did not make it in to ~/.bash_profile
2. If I run "helm init --client-only" it initializes to ~/.helm, but then when I try to install something it complains because the *.pem files are not found in ~/.helm.
3. If I set HELM_HOME=/usr/local/bin/helm like the install attempts to do, helm complains that $HELM_HOME must be a directory, and in this case it's the binary.

The problems above are with the default config from the Vagrantfile.

Now, if I try and configure helm via cloudctl per the ICp documentation.

```
cloudctl login -n default -u admin -p admin -a https://192.168.27.100:8443 --skip-ssl-validation -c "id-mycluster-account"
helm init --client-only
helm repo add ibmcase https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce
helm upgrade --install bluecompute ibmcase/bluecompute-ce --tls
```
I see the following error.

Error: UPGRADE FAILED: incompatible versions client[v2.11.0] server[v2.9.1+icp]

It looks like the helm install of v2.11 is incompatible with the server version of Helm.

**Comment by ahmadnurus** [comment]
I have same issue. after upgrade the tiller `helm init --upgrade` it's work perfectly

**Comment by doormat18** [comment]
> 
> 
> I have same issue. after upgrade the tiller `helm init --upgrade` it's work perfectly

Isn't tiller part of ICp? I wouldn't think upgrading it independent of the rest of the software would be a good idea. Maybe I'm wrong, I'm new to this.

Here's the install_helm code I used in Vagrant.

sudo curl -kLo /tmp/helm.tar.gz https://#{base_segment}.100:8443/api/cli/helm-linux-amd64.tar.gz
sudo tar xzf /tmp/helm.tar.gz -C /tmp/
sudo mv /tmp/linux-amd64/helm /usr/local/bin/helm
sudo rm -f /tmp/helm.tar.gz
sudo rm -rf /tmp/linux-amd64/
export HELM_HOME=~/.helm &> /dev/null
echo "HELM_HOME=~/.helm" >> ~/.bash_profile &> /dev/null
sudo chown -R vagrant:vagrant /usr/local/bin/helm &> /dev/null
cloudctl login -n default -u admin -p admin -a https://#{base_segment}.100:8443 --skip-ssl-validation -c "id-mycluster-account"
helm init --client-only &> /dev/null

**Comment by ahmadnurus** [comment]
I found that solution from the following troubleshooting https://github.com/ibm-cloud-architecture/refarch-integration/blob/master/docs/icp/troubleshooting.md#helm-incompatible-version

**Comment by EvilCreamsicle** [comment]
For what its worth, it seems to me that 'upgrade your server version to match your client' is not a great solution. Just upgrading your server version is not always an option.
