### ISSUE TITLE
Issues with SSL certificates installing using Vagrant

### ISSUE THREAD

**Issue by johnbuckley** [IBM/deploy-ibm-cloud-private#193]
My customer is having SSL certificate issues installing using Vagrant

Initial error was
> The box 'bento/ubuntu-16.04' could not be found or
could not be accessed in the remote catalog.  If this is a private
box on Hashicorp's Vagrant Cloud, please verify you're logged in via
'vagrant login'.  Also , please double-check the name.  The expanded
URL and error message are shown below: 
>
> URL: ["https://vagrantcloud.com/bento/ubuntu-16.04"]
Error: SSL certificate problem: self signed certificate in certificate chain

which we got around by adding the following line to the Vagrantfile
> config.vm.box_download_insecure=true

However, now we get this error
>icp: Error: Failed container creation: Get https://cloud-images.ubuntu.com/releases/streams/v1/index.json: x509: certificate signed by unknown authority
>
>  icp: Creating worker2
>
>  icp: Error: Failed container creation: Get https://cloud-images.ubuntu.com/releases/streams/v1/index.json: x509: certificate signed by unknown authority
>
>The SSH command responded with a non-zero exit status. Vagrant

What advice should I give customer regarding what needs to be trusted

**Comment by berenss** [comment]
@johnbuckley John can you post the `vagrantfile`
you deploying 312 or 311?

**Comment by berenss** [comment]
@johnbuckley I think it would be more interesting to resolve the initial problem (`The box 'bento/ubuntu-16.04' could not be found or could not be accessed in the remote catalog`) and **not** do the adding of the line

> config.vm.box_download_insecure=true

In my case I can get to the 'bento/ubuntu-16.04'

> 
> ==> icp: Box 'bento/ubuntu-16.04' could not be found. Attempting to find and install...
>     icp: Box Provider: virtualbox
>     icp: Box Version: 201812.27.0
> ==> icp: Loading metadata for box 'bento/ubuntu-16.04'
>     icp: URL: https://vagrantcloud.com/bento/ubuntu-16.04
> ==> icp: Adding box 'bento/ubuntu-16.04' (v201812.27.0) for provider: virtualbox
>     icp: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/201812.27.0/providers/virtualbox.box
> ==> icp: Successfully added box 'bento/ubuntu-16.04' (v201812.27.0) for 'virtualbox'!
> ==> icp: Importing base box 'bento/ubuntu-16.04'...

Perhaps we can try a workaround to grab that base image first,
`wget https://app.vagrantup.com/bento/boxes/ubuntu-16.04/versions/201812.27.0/providers/virtualbox.box`

then add the box:
`vagrant box add virtualbox.box --name bento/ubuntu-16.04`

then proceed with the `vagrant up`

**Comment by johnbuckley** [comment]
@berenss We started with this version of the Vagrant file
https://github.com/IBM/deploy-ibm-cloud-private/blob/9295ed3d9ee7bc6f0a84e6f300765b7e3041b6dc/Vagrantfile
and did a `vagrant box add` of the box initially which seems to be ignored during `vagrant up` so we tried the config.vm.box_download_insecure option which got the correct box but then failed later as shown.  We can access https://cloud-images.ubuntu.com/releases/streams/v1/index.json from the browser without certificate issues.

**Comment by berenss** [comment]
hey @johnbuckley better way to add the box is this:
`vagrant box add bento/ubuntu-16.04`
then select type `3) virtualbox`
you can check the resulting list, 
`vagrant box list`
and use eg prune, to clean up all old versions,
`vagrant box prune` 
or to remove any specific version that looks fouled or have no version string,
`vagrant box remove bento/ubuntu-18.04 --box-version VALUE `

**Comment by berenss** [comment]
to your 2nd issue (the one you get after the bento/ubuntu-16.04 box is sorted out,
what do you get if you try to add this line in bold:
boot_lxd_worker_nodes = <<SCRIPT
**dig cloud-images.ubuntu.com**
lxc launch -p default -p worker1 ubuntu:16.04 worker1
lxc launch -p default -p worker2 ubuntu:16.04 worker2
SCRIPT

**Comment by berenss** [comment]
I'm guessing a network rule blocks the  http request, something along the lines of this: https://github.com/lxc/lxd/issues/4246#issuecomment-365496803

**Comment by johnbuckley** [comment]
@berenss below is the result of adding that line

>
>icp: Running: script: boot_lxd_worker_nodes
>
>    icp:
>
>    icp: ; <<>> DiG 9.10.3-P4-Ubuntu <<>> cloud-images.ubuntu.com
>
>    icp: ;; global options: +cmd
>
>    icp: ;; Got answer:
>
>    icp: ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65355
>
>    icp: ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
>
>    icp:
>
>    icp: ;; OPT PSEUDOSECTION:
>
>    icp: ; EDNS: version: 0, flags:; udp: 4096
>
>    icp: ;; QUESTION SECTION:
>
>    icp: ;cloud-images.ubuntu.com.      IN      A
>
>    icp:
>
>    icp: ;; ANSWER SECTION:
>
>    icp: cloud-images.ubuntu.com. 600   IN      A       91.189.92.141
>
>    icp:
>
>    icp: ;; Query time: 43 msec
>
>    icp: ;; SERVER: 192.168.27.100#53(192.168.27.100)
>
>    icp: ;; WHEN: Mon Feb 25 14:07:55 UTC 2019
>
>    icp: ;; MSG SIZE  rcvd: 68
>
>    icp: To start your first container, try: lxc launch ubuntu:18.04
>
>    icp: Creating worker1
>
>    icp: Error: Failed container creation: Get https://cloud-images.ubuntu.com/releases/streams/v1/index.json: x509: certificate signed by unknown authority
>
>    icp: Creating worker2
>
>    icp: Error: Failed container creation: Get https://cloud-images.ubuntu.com/releases/streams/v1/index.json: x509: certificate signed by unknown authority
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

**Comment by berenss** [comment]
thx @johnbuckley did you see my comment here: https://github.com/IBM/deploy-ibm-cloud-private/issues/193#issuecomment-465793406

**Comment by naomizenge** [comment]
I got the same SSH error by git clone of this repository and `vagrant up` with VirtualBox 5.2.26, Vagrant 2.2.3 on MacBook Pro.
There are source code diff and patches in  [lxc/lxd#4246 (comment)](https://github.com/lxc/lxd/issues/4246#issuecomment-365496803) but don't know how to apply it in ICP environment.

**Comment by berenss** [comment]
@naomizenge did you mean `SSL error` as noted in the name of this git issue?

what I can say is that I did not get any SSL error. and I suspect that those getting the SSL error have a network rule that prevents the outbound http request from reaching http://cloud-images.ubuntu.com, so then it falls back to using https and that faces the SSL signing problem.

**Comment by naomizenge** [comment]
@berenss 
Thank you the reply and understood your thoughts.

Yes, I encountered the same error "The SSH command responded with a non-zero exit status..." at Creating worker1 and worker2.

I'll check the network related settings.

**Comment by johnbuckley** [comment]
Thx @berenss.  However a `curl http://cloud-images.ubuntu.com` appears to return content without any issue.

**Comment by naomizenge** [comment]
@johnbuckley 
I could resolve this issue by installing openssl package. Try below steps:
1. $ vagrant destroy
2. Search `openssh-server` in `Vagrantfile` and add `openssl` after it. So it will be
```
udo apt-get install --yes --quiet --target-release=xenial-backports lxd lxd-client bridge-utils dnsmasq thin-provisioning-tools \
    curl linux-image-extra-$(uname -r) linux-image-extra-virtual apt-transport-https ca-certificates software-properties-common \
    docker-ce python-setuptools python-pip build-essential python-dev nfs-kernel-server nfs-common aufs-tools ntp criu ipvsadm \
    rng-tools util-linux socat openssh-server openssl
```
3. $ vagrant up

Sent PR #198
