### ISSUE TITLE
Setup in Mac gets stuck

### ISSUE THREAD

**Issue by sanguptaibm** [IBM/deploy-ibm-cloud-private#20]
The vagrant up gets stuck at ==> icp: Pulling ibmcom/icp-datastore:2.1.0-beta-3... for ever with no movement even after 1 hr.

docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Sandips-MacBook-Air:~ sandipgupta$ vagrant version
Installed Version: 2.0.0
Latest Version: 2.0.0
 You're running an up-to-date version of Vagrant!

==> icp: This process will take approximately 10-20 minutes depending on network speeds.
==> icp: Take a break and go grab a cup of coffee, we'll keep working on this while you're away ;-)
==> icp: .
==> icp: .
==> icp: .
==> icp: master.icp			 ready
==> icp: cfc-worker1.icp		 ready
==> icp: cfc-worker2.icp		 ready
==> icp: cfc-manager1.icp		 ready
==> icp: Running provisioner: shell...
    icp: Running: script: precache_images
==> icp: Seeding IBM Cloud Private installation by pre-caching required docker images.
==> icp: This may take a few minutes depending on your connection speed and reliability.
==> icp: Pre-caching docker images....
==> icp: Pulling ibmcom/icp-inception:2.1.0-beta-3...
==> icp: Pulling ibmcom/icp-datastore:2.1.0-beta-3...

**Comment by sanguptaibm** [comment]
Sandips-MacBook-Air:deploy-ibm-cloud-private sandipgupta$ vagrant ssh
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-97-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

42 packages can be updated.
16 updates are security updates.


Last login: Sun Oct 15 06:19:49 2017 from 10.0.2.2
vagrant@master:~$ 

vagrant@master:~$ lxc list
+--------------+---------+-----------------------+------+------------+-----------+
|     NAME     |  STATE  |         IPV4          | IPV6 |    TYPE    | SNAPSHOTS |
+--------------+---------+-----------------------+------+------------+-----------+
| cfc-manager1 | RUNNING | 192.168.27.111 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-----------------------+------+------------+-----------+
| cfc-worker1  | RUNNING | 192.168.27.101 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-----------------------+------+------------+-----------+
| cfc-worker2  | RUNNING | 192.168.27.102 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-----------------------+------+------------+-----------+


Install got stuck and net got disconnected. How do i know the setup is done successfully and how do i get the console.

**Comment by tpouyer** [comment]
there is an install log file saved at the home directory when you ssh into the box using `vagrant ssh`.  The log file name will be `icp_install_log` You should see at the bottom of that log a messsage that says installation was successful or it failed.  

The "pre-caching" of docker images can take a long time depending on your internet connection speeds.  The `icp-datastore` images specifically is over 1.3GiB in size.

**Comment by sanguptaibm** [comment]
Hi.

I tried on a good network, the setup till icp-auth but then the mac hanged or was unresponsive. So after waiting for 1 hr, i had to restart.

From then onwards, after clearing and restarting, getting this error - 

==> icp: Err:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe i386 dnsmasq all 2.75-1ubuntu0.16.04.2
==> icp:   404  Not Found [IP: 91.189.88.152 80]
==> icp: Fetched 106 MB in 1min 16s (1,386 kB/s)
==> icp: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/n/ntp/ntp_4.2.8p4+dfsg-3ubuntu5.6_amd64.deb  404  Not Found [IP: 91.189.88.149 80]
==> icp: 
==> icp: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/a/aufs-tools/aufs-tools_3.2+20130722-1.1ubuntu1_amd64.deb  Hash Sum mismatch
==> icp: 
==> icp: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/d/dnsmasq/dnsmasq_2.75-1ubuntu0.16.04.2_all.deb  404  Not Found [IP: 91.189.88.152 80]
==> icp: 
==> icp: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux-meta/linux-image-generic_4.4.0.92.97_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
==> icp: 
==> icp: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux-meta/linux-image-extra-virtual_4.4.0.92.97_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
==> icp: 
==> icp: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> icp: sed: can't read /etc/systemd/system/multi-user.target.wants/docker.service: No such file or directory
==> icp: Failed to restart docker.service: Unit docker.service not found.
==> icp: sudo: pip: command not found
==> icp: sudo: pip: command not found
==> icp: usermod: group 'docker' does not exist
==> icp: newgrp: group 'docker' does not exist
==> icp: Failed to restart ntp.service: Unit ntp.service not found.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.


Any temporary file to be cleared or some thing else.

**Comment by sanguptaibm** [comment]
I also see  these issues in the above trace - 


 Packages [5,896 B]
==> icp: Get:30 http://archive.ubuntu.com/ubuntu xenial-backports/universe i386 Packages [5,896 B]
==> icp: Get:31 http://archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [3,060 B]
==> icp: Fetched 2,508 kB in 2min 20s (17.9 kB/s)
==> icp: Reading package lists...
==> icp: E
==> icp: : 
==> icp: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-i386/by-hash/SHA256/a158d9528ab153189739b9b1ef383dd01d770f1860ec6d95532880fb45d6aff9  Hash Sum mismatch
==> icp: E
==> icp: : 
==> icp: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/i18n/by-hash/SHA256/0f33303ae6adc4d5d4f709cec1666a344ea10f74c9e5b2dd304084162b76ba6e  
==> icp: E
==> icp: : 
==> icp: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/restricted/binary-amd64/by-hash/SHA256/a45c3c11577c260c715dfe3a172f1d82a5bdff955ec260fb09ee91f0bd8c82de  
==> icp: E
==> icp: : 
==> icp: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/by-hash/SHA256/b9b2af18177ebfe8d29023d7aa08109ab8687f023ec63a01b11bc32f92874682  Hash Sum mismatch
==> icp: E
==> icp: : 
==> icp: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-i386/by-hash/SHA256/37e941bda598fb2789ae3837e7237f3c270b08f15c666d7dd7e2ecd44a4b2175  
==> icp: E
==> icp: : 
==> icp: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/i18n/by-hash/SHA256/59153f3ef0c30543c59b3c9edcbecf70f1c103cf94591f038965e52c64bcd722  
==> icp: E
==> icp: : 
==> icp: Some index files failed to download. They have been ignored, or old ones used instead.
==> icp: Reading package lists...
==> icp: Building dependency tree...
==> icp: 
==> icp: Reading state information...
==> icp: ca-certificates is already the newest version (20160104ubuntu1).
==> icp: apt-transport-https is already the newest version (1.2.24).
==> icp: curl is already the newest version (7.47.0-1ubuntu2.2).
==> icp: linux-image-extra-4.4.0-92-generic is already the newest version (4.4.0-92.115).
==> icp: linux-image-extra-4.4.0-92-generic set to manually installed.
==> icp: nfs-common is already the newest version (1:1.2.8-9ubuntu12.1).
==> icp: software-properties-common is already the newest version (0.96.20.7).
==> icp: The following packages were automatically installed and are no longer required:
==> icp:   fakeroot libfakeroot libfile-fcntllock-perl ncurses-term os-prober
==> icp:   python3-requests python3-urllib3 ssh-import-id tcpd
==> icp: Use 'sudo apt autoremove' to remove them.
==> icp: The following additional packages will be installed:
==> icp:   dpkg-dev ebtables g++ g++-5 libaio1 libexpat1-dev libltdl7 libopts25
==> icp:   libpython-dev libpython2.7 libpython2.7-dev libstdc++-5-dev linux-firmware
==> icp:   linux-image-generic python-pip-whl python-pkg-resources python2.7-dev
==> icp:   xdelta3
==> icp: Suggested packages:

**Comment by tpouyer** [comment]
if the install failed the best thing to do is to execute a `vagrant destroy` and then `vagrant up`

**Comment by sanguptaibm** [comment]
Now it is at this step.

Retrieving image: rootfs: 100% (765.53kB/s)
                                            
Retrieving image: rootfs: 100% (765.53kB/s)
                                            
==> icp: Starting cfc-manager1
==> icp: Creating cfc-worker1
==> icp: 
==> icp: Starting cfc-worker1
==> icp: Creating cfc-worker2
==> icp: 
==> icp: Starting cfc-worker2
==> icp: Running provisioner: shell...
    icp: Running: script: wait_for_worker_nodes_to_boot
==> icp: Preparing nodes for IBM Cloud Private community edition cluster installation.
==> icp: This process will take approximately 10-20 minutes depending on network speeds.
==> icp: Take a break and go grab a cup of coffee, we'll keep working on this while you're away ;-)
==> icp: .
==> icp: .
==> icp: .
==> icp: .

But this is going on icp......

**Comment by tpouyer** [comment]
Yes, so this step is preparing the nodes by install pre-requisite software onto the master and worker nodes.  This will take a few minutes then it will proceed with pre-caching icp docker images required for installation (that may take a while as some of the images are quite large >1GiB) then once those images have been pulled the ICP installation will begin.  All installs occur on the VirtualBox vm stood up by the vagrant file.

**Comment by sanguptaibm** [comment]
==> icp: .
==> icp: .
==> icp: .
==> icp: master.icp			 ready
==> icp: cfc-worker1.icp		 ready
==> icp: cfc-worker2.icp		 ready
==> icp: cfc-manager1.icp		 ready
==> icp: Running provisioner: shell...
    icp: Running: script: precache_images
==> icp: Seeding IBM Cloud Private installation by pre-caching required docker images.
==> icp: This may take a few minutes depending on your connection speed and reliability.
==> icp: Pre-caching docker images....
==> icp: Pulling ibmcom/icp-inception:2.1.0-beta-3...

**Comment by sanguptaibm** [comment]
==> icp: Running provisioner: shell...
    icp: Running: script: precache_images
==> icp: Seeding IBM Cloud Private installation by pre-caching required docker images.
==> icp: This may take a few minutes depending on your connection speed and reliability.
==> icp: Pre-caching docker images....
==> icp: Pulling ibmcom/icp-inception:2.1.0-beta-3...
==> icp: Pulling ibmcom/icp-datastore:2.1.0-beta-3...
==> icp: Pulling ibmcom/icp-platform-auth:2.1.0-beta-3...
==> icp: Pulling ibmcom/icp-auth:2.1.0-beta-3...


After this step, the Mac becomes unresponsive and I left it for 2 hrs, still same and hence had to force restart.

Pls let me know how can I get it setup on Mac.

**Comment by sanguptaibm** [comment]
This is what i get from vagrant provision- 

==> icp: Firewall stopped and disabled on system startup
==> icp: error: Invalid preseed YAML content
==> icp: Running provisioner: shell...
    icp: Running: script: bring_up_icp_host_interface
==> icp: Running provisioner: shell...
    icp: Running: script: set_dnsnameserver_to_lxd_dnsmasq
==> icp: Running provisioner: shell...
    icp: Running: script: configure_icp_install
==> icp: Running provisioner: shell...
    icp: Running: script: boot_lxd_worker_nodes
==> icp: Creating cfc-manager1
==> icp: 
==> icp: error: Failed container creation:
==> icp:  - https://cloud-images.ubuntu.com/releases: Container 'cfc-manager1' already exists
==> icp: Creating cfc-worker1
==> icp: error: Failed container creation:
==> icp:  - https://cloud-images.ubuntu.com/releases: Container 'cfc-worker1' already exists
==> icp: Creating cfc-worker2
==> icp: 
==> icp: error: Failed container creation:
==> icp:  - https://cloud-images.ubuntu.com/releases: Container 'cfc-worker2' already exists
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Sandips-MacBook-Air:deploy-ibm-cloud-private sandipgupta$ vagrant ssh
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-97-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

42 packages can be updated.
0 updates are security updates.


vagrant@master:~$ lxc list
+--------------+---------+--------------------------------+------+------------+-----------+
|     NAME     |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
+--------------+---------+--------------------------------+------+------------+-----------+
| cfc-manager1 | RUNNING | 192.168.27.111 (eth0)          |      | PERSISTENT | 0         |
|              |         | 172.17.0.1 (docker0)           |      |            |           |
+--------------+---------+--------------------------------+------+------------+-----------+
| cfc-worker1  | RUNNING | 192.168.27.101 (eth0)          |      | PERSISTENT | 0         |
+--------------+---------+--------------------------------+------+------------+-----------+
| cfc-worker2  | RUNNING | 192.168.27.102 (eth0)          |      | PERSISTENT | 0         |
+--------------+---------+--------------------------------+------+------------+-----------+
vagrant@master:~$ 

Now how do i get the ICP setup done.

**Comment by sanguptaibm** [comment]
vagrant@master:~$ docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
ibmcom/icp-inception       2.1.0-beta-3        7dcfd9a564b2        7 days ago          441MB
ibmcom/icp-datastore       2.1.0-beta-3        ebe697aa6df8        11 days ago         1.69GB
ibmcom/icp-platform-auth   2.1.0-beta-3        600f40bda236        11 days ago         492MB
vagrant@master:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-97-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796GiB
Name: master
ID: 64WD:MQPS:FTN6:UMEO:AUCM:GDNZ:57QL:WNCO:Z6EM:7JN3:D6IH:XLU4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

vagrant@master:~$

**Comment by tpouyer** [comment]
If the `vagrant up` fails you MUST run `vagrant destroy` before attempting to run `vagrant up` again.  The vagrant file attempts to "pre-pull" some of the docker images that the ICP installer will need prior to starting the ICP installer.  ( see code here https://github.com/IBM/deploy-ibm-cloud-private/blob/master/Vagrantfile#L591-L605 ) It does this because some users will experience a failure with the ICP installer due to slow speeds downloading images from Docker Hub, which is what you may be experiencing here.  

Have you tried to use the Cachefile setup explained here:  https://github.com/IBM/deploy-ibm-cloud-private#advanced-cache-setup  Using the passthrough cache will help if you have to run this vagrant file multiple times as it caches the downloads from the internet onto a separate local server.

I don't know why your laptop is freezing after pulling the icp-auth image from docker hub.  Have you looked at your disk space to make sure you have enough? Have you tried pulling these images onto your laptop using `docker pull` to see how quickly they are downloading for you? Just because you are on a "good" network does not mean docker hub downloads will be "fast" it depends on which cache server docker is sending you to for the downloads which neither you or I can control.

How much RAM are you allocating to the `Vagrantfile` using https://github.com/IBM/deploy-ibm-cloud-private/blob/master/Vagrantfile#L19

How much CPU are you allocating to the `Vagrantfile` using https://github.com/IBM/deploy-ibm-cloud-private/blob/master/Vagrantfile#L11

**Comment by sanguptaibm** [comment]
Hi,
Changed RAM to 4 GB and CPU to '2'.

Reached past all the issues - but got this final error. Pls help.

==> icp: TASK [addon : Ensuring that directory /installer/playbook/..//cluster/cfc-components/helm/ exist] ***
==> icp: changed: [localhost]
==> icp: 
==> icp: TASK [addon : Ensure Helm service files exist] *********************************
==> icp: changed: [localhost] => (item=helm-api.yaml)
==> icp: changed: [localhost] => (item=helm-repo.yaml)
==> icp: 
==> icp: TASK [addon : Ensuring that the /installer/playbook/..//cluster/cfc-components/roles directory exist] ***
==> icp: changed: [localhost]
==> icp: 
==> icp: TASK [addon : Copying role files to /installer/playbook/..//cluster/cfc-components/roles] ***
==> icp: changed: [localhost]
==> icp: 
==> icp: TASK [addon : Creating rbac roles] *********************************************
==> icp: changed: [localhost]
==> icp: 
==> icp: TASK [addon : Adding label to master nodes] ************************************
==> icp: changed: [localhost] => (item=192.168.27.100)
==> icp: 
==> icp: TASK [addon : Adding label to proxy nodes] *************************************
==> icp: changed: [localhost] => (item=192.168.27.100)
==> icp: 
==> icp: TASK [addon : Adding label to management nodes] ********************************
==> icp: failed: [localhost] (item=192.168.27.111) => {"changed": true, "cmd": "kubectl label nodes 192.168.27.111 management=true --overwrite=true", "delta": "0:00:00.334015", "end": "2017-10-17 05:33:20.965612", "failed": true, "item": "192.168.27.111", "rc": 1, "start": "2017-10-17 05:33:20.631597", "stderr": "Error from server (NotFound): nodes \"192.168.27.111\" not found", "stderr_lines": ["Error from server (NotFound): nodes \"192.168.27.111\" not found"], "stdout": "", "stdout_lines": []}
==> icp: 
==> icp: PLAY RECAP *********************************************************************
==> icp: 192.168.27.100             : ok=195  changed=61   unreachable=0    failed=0   
==> icp: 192.168.27.101             : ok=0    changed=0    unreachable=1    failed=0   
==> icp: 192.168.27.102             : ok=0    changed=0    unreachable=1    failed=0   
==> icp: 192.168.27.111             : ok=0    changed=0    unreachable=1    failed=0   
==> icp: localhost                  : ok=109  changed=49   unreachable=0    failed=1   
==> icp: Playbook run took 0 days, 0 hours, 10 minutes, 57 seconds
==> icp: FATAL ERROR OCCURRED DURING INSTALLATION :-(
==> icp: 
==> icp: TASK [Checking Python interpreter] *********************************************
==> icp: changed: [192.168.27.100]
==> icp: fatal: [192.168.27.111] => Failed to connect to the host via ssh: ssh: connect to host 192.168.27.111 port 22: Host is unreachable
==> icp: fatal: [192.168.27.101] => Failed to connect to the host via ssh: ssh: connect to host 192.168.27.101 port 22: Host is unreachable
==> icp: fatal: [192.168.27.102] => Failed to connect to the host via ssh: ssh: connect to host 192.168.27.102 port 22: Host is unreachable
==> icp: 
==> icp: PLAY [Checking prerequisites] **************************************************
==> icp: The install log can be view with: 
==> icp: vagrant ssh
==> icp: cat icp_install_log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by tpouyer** [comment]
starting with beta-3 you'll need 8GiB ram and 4cpus to really make this work.  You can change the following variable in the `Vagrantfile`:

```
disabled_management_services = '["va"]'
```

to 

```
disabled_management_services = '["va","metering",“monitoring”]'
```

**Comment by sanguptaibm** [comment]
Hi,

After this, I have to again start with vagrant up.

or can I do some specific things from where it failed.

I tried caching, but it failed and hence reverted without caching.

**Comment by tpouyer** [comment]
Yes, it will be necessary to run vagrant destroy and vagrant up

**Comment by samuelleung** [comment]
> starting with beta-3 you'll need 8GiB ram and 4cpus to really make this work. 
My Mac only got 8GiB ram physically. I find if I put it as 8GB memory in Vagrantfile, it would stuck. But if I put it as 6GB, some nodes would be not accessible through the node checking at setup. Any idea?

**Comment by tpouyer** [comment]
If you set memory to 6GiB ram you will need to disable some services:
```
disabled_management_services = '["va","metering",“monitoring”]'
```

You can also try changing the `base_segment` value in the `Vagrantfile` to some other value like `192.168.56` b/c this might be a network issue you are seeing.

**Comment by samuelleung** [comment]
Cool. It works like a charm after disabling those services. Installed successfully. Thanks!

Just now I rebooted the node but found the management console is not available. Checked netstat  and found port 8443 is not listening. Do I need to start any service manually for the management console?

**Comment by tpouyer** [comment]
You can try to restart the docker service on the master node:

```
sudo systemctl restart docker.service
```

Others have reported this issue. It should be resolved with the GA release due out next week. Until then try to avoid using `vagrant halt` and use `vagrant suspend` instead to stop the vm.

**Comment by sanguptaibm** [comment]
Hi,

After keeping memory to 6GB and CPU to 4 and disabling those services, got the below error. What is your advice?

==> icp: TASK [addon : Adding label to proxy nodes] *************************************
==> icp: changed: [localhost] => (item=192.168.27.100)
==> icp: 
==> icp: TASK [addon : Adding label to management nodes] ********************************
==> icp: failed: [localhost] (item=192.168.27.111) => {"changed": true, "cmd": "kubectl label nodes 192.168.27.111 management=true --overwrite=true", "delta": "0:00:00.446473", "end": "2017-10-21 12:21:38.897801", "failed": true, "item": "192.168.27.111", "rc": 1, "start": "2017-10-21 12:21:38.451328", "stderr": "Error from server (NotFound): nodes \"192.168.27.111\" not found", "stderr_lines": ["Error from server (NotFound): nodes \"192.168.27.111\" not found"], "stdout": "", "stdout_lines": []}
==> icp: 
==> icp: PLAY RECAP *********************************************************************
==> icp: 192.168.27.100             : ok=195  changed=61   unreachable=0    failed=0   
==> icp: 192.168.27.101             : ok=0    changed=0    unreachable=1    failed=0   
==> icp: 192.168.27.102             : ok=0    changed=0    unreachable=1    failed=0   
==> icp: 192.168.27.111             : ok=0    changed=0    unreachable=1    failed=0   
==> icp: localhost                  : ok=109  changed=49   unreachable=0    failed=1   
==> icp: 
==> icp: Playbook run took 0 days, 0 hours, 13 minutes, 1 seconds
==> icp: FATAL ERROR OCCURRED DURING INSTALLATION :-(
==> icp: 
==> icp: TASK [Checking Python interpreter] *********************************************
==> icp: changed: [192.168.27.100]
==> icp: fatal: [192.168.27.102] => Failed to connect to the host via ssh: ssh: connect to host 192.168.27.102 port 22: Host is unreachable
==> icp: fatal: [192.168.27.101] => Failed to connect to the host via ssh: ssh: connect to host 192.168.27.101 port 22: Host is unreachable
==> icp: fatal: [192.168.27.111] => Failed to connect to the host via ssh: ssh: connect to host 192.168.27.111 port 22: Host is unreachable
==> icp: 
==> icp: PLAY [Checking prerequisites] **************************************************
==> icp: The install log can be view with: 
==> icp: vagrant ssh
==> icp: cat icp_install_log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by tpouyer** [comment]
This error suggests that the lxc nodes did not install properly all the prereqs.  You can view the logs for the lxc nodes by running the following:

```
lxc exec cfc-worker1 -- cat /var/log/cloud-init-output.log
```

You can replace cfc-worker1 above with all the lxc node names: `cfc-worker2`, `cfc-manager1`

Did you run `vagrant destroy` before running `vagrant up` after making the changes described above?

**Comment by tpouyer** [comment]
@sanguptaibm you might need to change your `base_segment` value in the `Vagrantfile` to something like `base_segment = '192.168.56'` It's possible that there is a network segment conflict which is preventing the lxc nodes from being connected to the external network correctly and preventing the prereq software from being able to be downloaded and installed on the lxc nodes prior to kicking off the ICP installation.

**Comment by sanguptaibm** [comment]
Hi,

Finally got it working when I again started by setting the base_segment='192.68.56'.
RAM = 6GB, CPU=4 & disabled_management_services = '["va","metering",“monitoring”]'.

Got the console up and able to login to it. Thanks for all the help.
