### ISSUE TITLE
Installation stuck on Win7 64

### ISSUE THREAD

**Issue by hmagph** [IBM/deploy-ibm-cloud-private#21]
Tried the default steps in a Windows shell (git clone, vagrant up), and after initial license agreement, nothing happened for quite some time.

After restarting in "vagrant up --debug" mode, I noticed some symptoms that I could search help for, and found this corresponding information https://github.com/hashicorp/vagrant/issues/8783

Thus installed powershell 6.0.0 (or better), started it in administrator mode.
Given previous attempts to install ICP, I cleared vagrant and virtual box
  - clear vagrant folder: %USERHOME%\.vagrant.d\
  - clear virtualbox image: ubuntu-16.04-amd64 

Then ran "vagrant up --debug", and it ran almost until the end, but failed with this error:

```
Manage.exe: error: Could not rename the directory 'C:\\Users\\IBM_ADMIN\\Virtual
Box VMs\\ubuntu-16.04-amd64_1508412122173_40549' to 'C:\\Users\\IBM_ADMIN\\Virtu
alBox VMs\\IBM-Cloud-Private-dev-edition' to save the settings file (VERR_ALREAD
Y_EXISTS)\r\nVBoxManage.exe: error: Details: code E_FAIL (0x80004005), component
 SessionMachine, interface IMachine, callee IUnknown\r\nVBoxManage.exe: error: C
ontext: \"SaveSettings()\" at line 3052 of file VBoxManageModifyVM.cpp\r\n"]
```

**Comment by hmagph** [comment]
Complete log:

`
VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\Users\IBM_ADMIN\Virtua
lBox VMs\ubuntu-16.04-amd64_1508412122173_40549' to 'C:\Users\IBM_ADMIN\VirtualB
ox VMs\IBM-Cloud-Private-dev-edition' to save the settings file (VERR_ALREADY_EX
ISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachi
ne, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3052 of file VBoxManage
ModifyVM.cpp

 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-ab864614e4765362808e957
9c11493d4
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00
000007481028>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VirtualBoxNameExists: The name of your virtual
 machine couldn't be set because VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\Users\IBM_ADMIN\Virtua
lBox VMs\ubuntu-16.04-amd64_1508412122173_40549' to 'C:\Users\IBM_ADMIN\VirtualB
ox VMs\IBM-Cloud-Private-dev-edition' to save the settings file (VERR_ALREADY_EX
ISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachi
ne, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3052 of file VBoxManage
ModifyVM.cpp
>
ERROR vagrant: The name of your virtual machine couldn't be set because VirtualB
ox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\Users\IBM_ADMIN\Virtua
lBox VMs\ubuntu-16.04-amd64_1508412122173_40549' to 'C:\Users\IBM_ADMIN\VirtualB
ox VMs\IBM-Cloud-Private-dev-edition' to save the settings file (VERR_ALREADY_EX
ISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachi
ne, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3052 of file VBoxManage
ModifyVM.cpp

ERROR vagrant: C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/pro
viders/virtualbox/driver/version_5_0.rb:650:in `rescue in block in set_name'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/driver/version_5_0.rb:643:in `block in set_name'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/retryable
.rb:17:in `retryable'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/driver/version_5_0.rb:642:in `set_name'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/set_name.rb:42:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/clean_machine_folder.rb:17:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/check_accessible.rb:18:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder
.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:1
9:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin
/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder
.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:1
9:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin
/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder
.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:1
9:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin
/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin
/box_check_outdated.rb:23:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin
/config_validate.rb:25:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/check_virtualbox.rb:17:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/match_mac_address.rb:19:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/discard_state.rb:15:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/import.rb:74:in `import'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/import.rb:13:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/prepare_clone_snapshot.rb:17:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin
/prepare_clone.rb:15:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/customize.rb:40:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/check_accessible.rb:18:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder
.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:1
9:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin
/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin
/config_validate.rb:25:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin
/handle_box.rb:56:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder
.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:1
9:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin
/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualb
ox/action/check_virtualbox.rb:17:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.
rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder
.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:1
9:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.
rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:227
:in `action_raw'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:202
:in `block in action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb
:631:in `lock'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:188
:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:188
:in `action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/batch_action.r
b:82:in `block (2 levels) in run'
 INFO interface: error: The name of your virtual machine couldn't be set because
 VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\Users\IBM_ADMIN\Virtua
lBox VMs\ubuntu-16.04-amd64_1508412122173_40549' to 'C:\Users\IBM_ADMIN\VirtualB
ox VMs\IBM-Cloud-Private-dev-edition' to save the settings file (VERR_ALREADY_EX
ISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachi
ne, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3052 of file VBoxManage
ModifyVM.cpp

The name of your virtual machine couldn't be set because VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\Users\IBM_ADMIN\Virtua
lBox VMs\ubuntu-16.04-amd64_1508412122173_40549' to 'C:\Users\IBM_ADMIN\VirtualB
ox VMs\IBM-Cloud-Private-dev-edition' to save the settings file (VERR_ALREADY_EX
ISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachi
ne, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3052 of file VBoxManage
ModifyVM.cpp
 INFO interface: Machine: error-exit ["Vagrant::Errors::VirtualBoxNameExists", "
The name of your virtual machine couldn't be set because VirtualBox\nis reportin
g another VM with that name already exists. Most of the\ntime, this is because o
f an error with VirtualBox not cleaning up\nproperly. To fix this, verify that n
o VMs with that name do exist\n(by opening the VirtualBox GUI). If they don't, t
hen look at the\nfolder in the error message from VirtualBox below and remove it
\nif there isn't any information you need in there.\n\nVirtualBox error:\n\nVBox
Manage.exe: error: Could not rename the directory 'C:\\Users\\IBM_ADMIN\\Virtual
Box VMs\\ubuntu-16.04-amd64_1508412122173_40549' to 'C:\\Users\\IBM_ADMIN\\Virtu
alBox VMs\\IBM-Cloud-Private-dev-edition' to save the settings file (VERR_ALREAD
Y_EXISTS)\r\nVBoxManage.exe: error: Details: code E_FAIL (0x80004005), component
 SessionMachine, interface IMachine, callee IUnknown\r\nVBoxManage.exe: error: C
ontext: \"SaveSettings()\" at line 3052 of file VBoxManageModifyVM.cpp\r\n"]
PS E:\data\devops\git\deploy-ibm-cloud-private>`

**Comment by tpouyer** [comment]
You need to also delete the folders in the directory %USERHOME%\Virtualbox VMs\

Then run vagrant destroy and vagrant up

**Comment by hmagph** [comment]
Thanks for the clue @tpouyer . It definitely helps.
Script has been installing for 20mn, and now seeing:

```
 INFO interface: info: FAILED - RETRYING: TASK: addon : Waiting for platform aut
h service (23 retries left).
 INFO interface: info: ==> icp: FAILED - RETRYING: TASK: addon : Waiting for pla
tform auth service (23 retries left).
==> icp: FAILED - RETRYING: TASK: addon : Waiting for platform auth service (23
retries left).
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
 INFO interface: info: FAILED - RETRYING: TASK: addon : Waiting for platform aut
h service (22 retries left).
 INFO interface: info: ==> icp: FAILED - RETRYING: TASK: addon : Waiting for pla
tform auth service (22 retries left).
==> icp: FAILED - RETRYING: TASK: addon : Waiting for platform auth service (22
retries left).
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
 INFO interface: info: FAILED - RETRYING: TASK: addon : Waiting for platform aut
h service (21 retries left).
 INFO interface: info: ==> icp: FAILED - RETRYING: TASK: addon : Waiting for pla
tform auth service (21 retries left).
==> icp: FAILED - RETRYING: TASK: addon : Waiting for platform auth service (21
retries left).
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
 INFO interface: info: FAILED - RETRYING: TASK: addon : Waiting for platform aut
h service (20 retries left).
 INFO interface: info: ==> icp: FAILED - RETRYING: TASK: addon : Waiting for pla
tform auth service (20 retries left).
==> icp: FAILED - RETRYING: TASK: addon : Waiting for platform auth service (20
retries left).
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...

```

**Comment by hmagph** [comment]
Finished still with a failure @tpouyer 

`C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:227:in `action_raw'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:202:in `block in action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:631:in `lock'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:188:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:188:in `action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantError", "The SSH command responded with a non-zero exit status. Vagrant\nassumes that this means the command failed. The output for this command\nshould be in the log above. Please read the output to determine what\nwent wrong."]
PS E:\data\devops\git\deploy-ibm-cloud-private>
`

**Comment by tpouyer** [comment]
@hmagph this looks like a Vagrant error not related to this particular `Vagrantfile`. Can you create an empty directory and try running `vagrant init bento/ubuntu-16.04` and `vagrant up` to ensure that the basic vagrant setup is working for you.

**Comment by hmagph** [comment]
Vagrant is fine. I finally managed to set it up using this command line:

vagrant up --provider=virtualbox

(ensuring using VirtualBox 5.1.x)
