### ISSUE TITLE
Vagrant file for installing ICP EE

### ISSUE THREAD

**Issue by pexus** [IBM/deploy-ibm-cloud-private#217]
Is there a Vagrant file for installing the ICP EE Tar File?
I have sufficiently large capacity laptop and was looking to use Vagrant to install the ICP EE for demo purpose as I need to use Vulnerability Advisor which is not available in CE version. I did make some changes to this Vagrant file which is for installing the ICP CE. I have not been successful as I am running out of disk space with the default configuration. I did try to increase the base storage to 150GB from default 64GB. Being a newbie to Vagrant I am not able to clearly see the changes required to Install ICP EE. Has anyone tried this or is this even possible?
Thank you in advance

**Comment by pexus** [comment]
Here is my current LV and cddisk info.  The root is allocated only 64GB, though I have more space because I made changes to allocate 150GB disk when creating the VM
---
--- Logical volume ---
  LV Path                /dev/vagrant-vg/root
  LV Name                root
  VG Name                vagrant-vg
  LV UUID                YD6Xvu-bQna-TMxq-FI5E-edDk-NXeV-UGcamx
  LV Write Access        read/write
  LV Creation host, time vagrant, 2018-12-28 18:31:40 +0000
  LV Status              available
  # open                 1
  LV Size                62.32 GiB
  Current LE             15955
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           252:0
  
  
  sudo lvresize -l +100%FREE /dev/mapper/vagrant--vg-root
  
  
                                      Disk: /dev/sda
                  Size: 150 GiB, 161061273600 bytes, 314572800 sectors
                           Label: dos, identifier: 0x8d02b53e

    Device         Boot           Start          End     Sectors    Size   Id Type
>>  /dev/sda1      *               2048      1499135     1497088    731M   83 Linux
    /dev/sda2                   1501182    134215679   132714498   63.3G    5 Extended
    └─/dev/sda5                 1501184    134215679   132714496   63.3G   8e Linux L
    Free space                134215680    314572799   180357120     86G

--

**Comment by pexus** [comment]
I looked at the Vagrant file I could not find how is the LV /dev/vagrant-vg/root getting allocated with 62.32 GB. I need to increase the size to use the full 150GB I have. Appreciate any pointers to do this so that I can re-attempt installing the ICP EE as currently I am running out of disk space with the following error when executing docker load of the EE Tar file
```
 Loaded image: ibmcom/k8s-prometheus-adapter-amd64:v0.2.1.1
    icp: Loaded image: ibmcom/metering-data-manager-amd64:3.1.2
    icp: Loaded image: ibmcom/notification-dispatcher-amd64:3.1.2
    icp: Loaded image: ibmcom/elasticsearch-plugin-searchguard-amd64:2.0.0-f2
    icp: Loaded image: ibmcom/icp-logstash-amd64:5.5.1-f2
    icp: Error processing tar file(exit status 1): write /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar: no space left on device

vagrant@master:/storage$ df -h
Filesystem                       Size  Used Avail Use% Mounted on
udev                             7.9G     0  7.9G   0% /dev
tmpfs                            1.6G   13M  1.6G   1% /run
/dev/mapper/vagrant--vg-root      62G   30G   29G  51% /
tmpfs                            7.9G     0  7.9G   0% /dev/shm
tmpfs                            5.0M     0  5.0M   0% /run/lock
tmpfs                            7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/sda1                        720M   83M  601M  13% /boot
tmpfs                            1.6G     0  1.6G   0% /run/user/1000
/dev/mapper/vagrant--vg-storage  493G   70M  467G   1% /storage
tmpfs                            100K     0  100K   0% /var/lib/lxd/shmounts
tmpfs                            100K     0  100K   0% /var/lib/lxd/devlxd
/dev/lxd/containers_worker1      148G  2.3G  138G   2% /var/lib/lxd/storage-pools/lxd/containers/worker1
/dev/lxd/containers_worker2      148G  2.3G  138G   2% /var/lib/lxd/storage-pools/lxd/containers/worker2

**Comment by tpouyer** [comment]
The 64GiB size is coming from the original vagrant base box.  To increase the size you’ll need to modify the base box like this:

https://gist.github.com/jj-meyer/a9d878b004542e825b47

Then you can reference your modified base box in the Vagrantfile here:

https://github.com/IBM/deploy-ibm-cloud-private/blob/master/Vagrantfile#L1191

And comment out the version reference here:

https://github.com/IBM/deploy-ibm-cloud-private/blob/master/Vagrantfile#L1192

**Comment by pexus** [comment]
Thank you for the pointers. Will try this and update.

**Comment by pexus** [comment]
I made some further progress on the disk resize. I had to make some changes to the Vagrantfile to align with the ICP EE install instructions. I am getting the following error, about SSH connection. 
I am not sure how this is different from the CE and EE. Appreciate any pointers.


```
TASK [Checking Python interpreter] *********************************************
     icp: fatal: [192.168.27.101]: UNREACHABLE! => changed=false
    icp:   msg: |-
    icp:     Failed to connect to the host via ssh: Permission denied (publickey).
    icp:   unreachable: true
    icp: fatal: [192.168.27.100]: UNREACHABLE! => changed=false
    icp:   msg: |-
    icp:     Failed to connect to the host via ssh: Permission denied (publickey,password).
    icp:   unreachable: true
    icp: fatal: [192.168.27.102]: UNREACHABLE! => changed=false
    icp:   msg: |-
    icp:     Failed to connect to the host via ssh: Permission denied (publickey).
    icp:   unreachable: true
    icp:
    icp: NO MORE HOSTS LEFT *************************************************************
    icp:
    icp: NO MORE HOSTS LEFT *************************************************************
    icp:
    icp: PLAY RECAP *********************************************************************
    icp: 192.168.27.100             : ok=0    changed=0    unreachable=1    failed=0
    icp: 192.168.27.101             : ok=0    changed=0    unreachable=1    failed=0
    icp: 192.168.27.102             : ok=0    changed=0    unreachable=1    failed=0
```
On doing vagrant ssh and doing the ssh manually I also see permission denied (publickey) error:

ssh -vv vagrant@192.168.27.101

```
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:tQTTQx5WqOnGzKakmuMuOwcRth9APdlv5rGonQGj73k
Warning: Permanently added '192.168.27.101' (ECDSA) to the list of known hosts.
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug2: key: /home/vagrant/.ssh/id_rsa (0x560d3f4d1bd0)
debug2: key: /home/vagrant/.ssh/id_dsa ((nil))
debug2: key: /home/vagrant/.ssh/id_ecdsa ((nil))
debug2: key: /home/vagrant/.ssh/id_ed25519 ((nil))
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/vagrant/.ssh/id_rsa
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
debug2: input_userauth_pk_ok: fp SHA256:/rfM+ZI5aly1Pfs5y2yWCkSlKTmHjbBDzBl/uT8f0ZA
debug1: Authentications that can continue: publickey
debug1: Trying private key: /home/vagrant/.ssh/id_dsa
debug1: Trying private key: /home/vagrant/.ssh/id_ecdsa
debug1: Trying private key: /home/vagrant/.ssh/id_ed25519
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey).
vagrant@master:~$ ls -l /home/vagrant/.ssh
total 16
-rw------- 1 vagrant vagrant  389 Jun  4 16:38 authorized_keys
-rw-rw-r-- 1 vagrant vagrant   69 Jun  7 18:03 config
-rw------- 1 vagrant vagrant 1676 Jun  7 18:03 id_rsa
-rw-rw-r-- 1 vagrant vagrant  389 Jun  7 18:03 id_rsa.pub
```

**Comment by pexus** [comment]
After many tries, I found that the default vagrant ssh keys was not working. I had to create a new key and append the pub key to authorized_keys file in master, worker1, and worker2 using the following script that I had to add into the Vagrantfile. With this new key the ssh vagrant@worker1, ssh vagrant@worker2 and ssh vagrant@master was working fine without the permission denied error.  May be the Enterprise edition requires the 4096 key length. the default vagrant ssh keys was using a smaller RSA key length?
```
sudo mkdir /opt/ibm-cloud-private-3.1.2
cd /opt/ibm-cloud-private-3.1.2
sudo mkdir /opt/ibm-cloud-private-3.1.2/cluster
ssh-keygen -b 4096 -f /home/vagrant/cluster/ssh_key -N ""
#Add this key to authorized_keys to master, worker1 and worker2
cat /home/vagrant/cluster/ssh_key.pub >> /home/vagrant/.ssh/authorized_keys
lxc file push /home/vagrant/cluster/ssh_key.pub worker1/tmp/ssh_key.pub
lxc exec worker1 -- sh -c "cat /tmp/ssh_key.pub >> /home/vagrant/.ssh/authorized_keys"
lxc file push /home/vagrant/cluster/ssh_key.pub worker2/tmp/ssh_key.pub
lxc exec worker2 -- sh -c "cat /tmp/ssh_key.pub >> /home/vagrant/.ssh/authorized_keys"
sudo cp -rv /home/vagrant/cluster/* /opt/ibm-cloud-private-3.1.2/cluster
sudo mkdir /opt/ibm-cloud-private-3.1.2/cluster/images
sudo mv /home/vagrant/ibm-cloud-private-x86_64-3.1.2.tar.gz /opt/ibm-cloud-private-3.1.2/cluster/images
echo "checking before install"
sudo docker run --net=host -t -e LICENSE=accept -v /opt/ibm-cloud-private-3.1.2/cluster:/installer/cluster ibmcom/icp-inception-amd64:3.1.2-ee check
```

**Comment by pradeepn-altran** [comment]
A modified script to install the ICP 3.1.2 is available from here:  https://github.com/pradeepn-altran/icp-ee-vagrant-install
