### ISSUE TITLE
Installation failing on Mac with Invalid UUID or filename

### ISSUE THREAD

**Issue by rs2015** [IBM/deploy-ibm-cloud-private#25]
MACBOOKPRO-20:deploy-ibm-cloud-private rpatel$ vagrant up
Bringing machine 'icp' up with 'virtualbox' provider...
==> icp: Importing base box 'bento/ubuntu-16.04'...
==> icp: Matching MAC address for NAT networking...
==> icp: Setting the name of the VM: IBM-Cloud-Private-dev-edition
==> icp: Fixed port collision for 22 => 2222. Now on port 2200.
==> icp: Clearing any previously set network interfaces...
==> icp: Preparing network interfaces based on configuration...
    icp: Adapter 1: nat
    icp: Adapter 2: hostonly
==> icp: Forwarding ports...
    icp: 22 (guest) => 2200 (host) (adapter 1)
==> icp: Running 'pre-boot' VM customizations...
A customization command failed:

["storageattach", :id, "--storagectl", "SATA Controller", "--port", 0, "--device", 0, "--type", "hdd", "--nonrotational", "on", "--medium", "/Users/rpatel/VirtualBox VMs/IBM-Cloud-Private-dev-edition/ubuntu-16.04-amd64-disk001.vmdk"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "34e4c878-2e42-4804-99ee-3648fd9be1d0", "--storagectl", "SATA Controller", "--port", "0", "--device", "0", "--type", "hdd", "--nonrotational", "on", "--medium", "/Users/rpatel/VirtualBox VMs/IBM-Cloud-Private-dev-edition/ubuntu-16.04-amd64-disk001.vmdk"]

Stderr: VBoxManage: error: Could not find file for the medium '/Users/rpatel/VirtualBox VMs/IBM-Cloud-Private-dev-edition/ubuntu-16.04-amd64-disk001.vmdk' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 179 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/Users/rpatel/VirtualBox VMs/IBM-Cloud-Private-dev-edition/ubuntu-16.04-amd64-disk001.vmdk"
>

Please fix this customization and try again.

**Comment by tpouyer** [comment]
Do you have a folder on your Mac like `/Users/rpatel/VirtualBox VMs/`?

**Comment by rs2015** [comment]
Hi Tim,

Yes folder exist. In fact, I was successfully able to deploy Cache VM. See attached screenshots.

Thanks for your help.

**Comment by tpouyer** [comment]
in the `/Users/rpatel/VirtualBox VMs/` folder do you see the following file structure?

```
IBM-Cloud-Private-dev-edition/ubuntu-16.04-amd64-disk001.vmdk
```
If not what files are in the `IBM-Cloud-Private-dev-edition` folder?

**Comment by rs2015** [comment]
No. I do not see this file - IBM-Cloud-Private-dev-edition/ubuntu-16.04-amd64-disk001.vmdk.

This is strange, I can see VM gets created in VirtualBox UI, but corresponding folder does not exist in /rpatel/VirtualBox VMs folder.

Thanks

**Comment by tpouyer** [comment]
I wonder if the VirtualBox home directory is somewhere else on your system?  

If you open VirtualBox on your mac then look in `VirtualBox -> Preferences -> General` what folder is listed as the `Default Machine Folder`?

**Comment by rs2015** [comment]
That was it. I forgot I had to change this directory to accommodate larger VMs. I changed it back, installation is now progressing.

Great find.

Thanks

**Comment by tpouyer** [comment]
:+1:
