### ISSUE TITLE
minor grammatical mistake in Vagrantfile line 486

### ISSUE THREAD

**Issue by berenss** [IBM/deploy-ibm-cloud-private#4]
`486  echo "Take a break and go grab a cup of coffee, we'll keep working on this while your away ;-)"`

should be "while **you're** away"

**Comment by tpouyer** [comment]
hahaha... Thx for the catch.  I'll update to correct the mistake.  I'm a bit dyslexic so I'm sure there will be more like this ;-)

**Comment by tpouyer** [comment]
Added in PR #6
