### ISSUE TITLE
Failed to install docker on lxc nodes...

### ISSUE THREAD

**Issue by 83810323** [IBM/deploy-ibm-cloud-private#46]
I'm using the vagrant deployment with icp-cache server. It seems everything goes right when deploying the icp server, however after some minutes docker installation seems to fail with the message:

[...]
==> icp: Preparing nodes for IBM Cloud Private community edition cluster installation.
==> icp: This process will take approximately 10-20 minutes depending on network speeds.
==> icp: Take a break and go grab a cup of coffee, we'll keep working on this while you're away ;-)
==> icp: .
==> icp: .
==> icp: .
==> icp: .
==> icp: .
==> icp: Failed to install docker on lxc nodes...
==> icp: Setting up crda (3.13-1) ...
==> icp: Setting up libltdl7:amd64 (2.4.6-0.1) ...
==> icp: Setting up docker-ce (17.09.0~ce-0~ubuntu) ...
==> icp: Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
==> icp: invoke-rc.d: initscript docker, action "start" failed.
==> icp: ● docker.service - Docker Application Container Engine
==> icp:    Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
==> icp: --
==> icp: Nov 06 15:48:43 cfc-worker1 systemd[1]: docker.service: Unit entered failed ....
==> icp: Nov 06 15:48:43 cfc-worker1 systemd[1]: docker.service: Failed with result '....
==> icp: Hint: Some lines were ellipsized, use -l to show in full.
==> icp: dpkg: error processing package docker-ce (--configure):
==> icp:  subprocess installed post-installation script returned error exit status 1
==> icp: Setting up keyutils (1.5.9-8ubuntu1) ...
==> icp: Setting up libexpat1-dev:amd64 (2.1.0-7ubuntu0.16.04.3) ...
==> icp: Setting up libpython2.7:amd64 (2.7.12-1ubuntu0.16.04.1) ...
==> icp: --
==> icp: Processing triggers for ureadahead (0.100.0-19) ...
==> icp: Errors were encountered while processing:
==> icp:  docker-ce
==> icp: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> icp: Cloud-init v. 0.7.9 running 'modules:final' at Mon, 06 Nov 2017 15:47:15 +0000. Up 12.0 seconds.
==> icp: 2017-11-06 15:49:30,700 - util.py[WARNING]: Failed to install packages: ['linux-image-extra-4.4.0-92-generic', 'linux-image-extra-virtual', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'docker-ce', 'python-setuptools', 'python-pip', 'build-essential', 'python-dev', 'aufs-tools', 'nfs-common']
==> icp: 2017-11-06 15:49:30,705 - cc_package_update_upgrade_install.py[WARNING]: Rebooting after upgrade or install per /var/run/reboot-required
==> icp: --
==> icp: ci-info: |   0   | 192.168.56.0 | 0.0.0.0 | 255.255.255.0 |    eth0   |   U   |
==> icp: ci-info: +-------+--------------+---------+---------------+-----------+-------+
==> icp: Cloud-init v. 0.7.9 running 'modules:config' at Mon, 06 Nov 2017 15:49:35 +0000. Up 2.0 seconds.
==> icp: Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
==> icp: Exception:
==> icp: Traceback (most recent call last):
==> icp:   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
==> icp: Setting up crda (3.13-1) ...
==> icp: Setting up libltdl7:amd64 (2.4.6-0.1) ...
==> icp: Setting up docker-ce (17.09.0~ce-0~ubuntu) ...
==> icp: Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
==> icp: invoke-rc.d: initscript docker, action "start" failed.
==> icp: ● docker.service - Docker Application Container Engine
==> icp:    Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
==> icp: --
==> icp: Nov 06 15:48:43 cfc-worker2 systemd[1]: docker.service: Unit entered failed ....
==> icp: Nov 06 15:48:43 cfc-worker2 systemd[1]: docker.service: Failed with result '....
==> icp: Hint: Some lines were ellipsized, use -l to show in full.

When entering into the VM:
vagrant@master:$ lxc list
+--------------+---------+-----------------------+------+------------+-----------+
|     NAME     |  STATE  |         IPV4          | IPV6 |    TYPE    | SNAPSHOTS |
+--------------+---------+-----------------------+------+------------+-----------+
| cfc-manager1 | RUNNING | 192.168.27.111 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-----------------------+------+------------+-----------+
| cfc-worker1  | RUNNING | 192.168.27.101 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-----------------------+------+------------+-----------+
| cfc-worker2  | RUNNING | 192.168.27.102 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-----------------------+------+------------+-----------+
vagrant@master:$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Mon 2017-11-06 16:02:24 UTC; 3min 48s ago
     Docs: https://docs.docker.com
  Process: 1832 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 1832 (code=exited, status=1/FAILURE)

Nov 06 16:02:24 master systemd[1]: docker.service: Unit entered failed state.
Nov 06 16:02:24 master systemd[1]: docker.service: Failed with result 'exit-code'.
Nov 06 16:02:24 master systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Nov 06 16:02:24 master systemd[1]: Stopped Docker Application Container Engine.
Nov 06 16:02:24 master systemd[1]: docker.service: Start request repeated too quickly.
Nov 06 16:02:24 master systemd[1]: Failed to start Docker Application Container Engine.

Can you help me?

**Comment by tpouyer** [comment]
can you try it without the icp-cache server by setting `use_cache` to `false`.  This may be an issue with how the scripts inject settings into the docker.service file on the lxc nodes. If you can successfully run the install with the `use_cache` set to `false` that will indicate a defect with how we are injecting the cache settings into the lxc nodes.

**Comment by 83810323** [comment]
If installing without the cache server, the problem no longer exists and ICp installs without problems
