### ISSUE TITLE
include link to public slack in the tail end of happy dance

### ISSUE THREAD

**Issue by berenss** [IBM/deploy-ibm-cloud-private#5]
"request access to the ICP-ce Public Slack!
direct link: http://ibm.biz/BdsHmN"

**Comment by berenss** [comment]
this is the real link, of the short one doesn't work:
https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W1559b1be149d_43b0_881e_9783f38faaff/page/Slack%20channel%20%28IBM%20Cloud%20technology%29%20sign%20up%20page

**Comment by tpouyer** [comment]
Added in PR #6
