### ISSUE TITLE
Unable to pull docker

### ISSUE THREAD

**Issue by bluegoose13** [IBM/deploy-ibm-cloud-private#52]
vagrant@master:~/cluster$ lxc list
+--------------+---------+-----------------------+------+------------+-----------+
|     NAME     |  STATE  |         IPV4          | IPV6 |    TYPE    | SNAPSHOTS |
+--------------+---------+-----------------------+------+------------+-----------+
| cfc-manager1 | RUNNING | 192.168.27.111 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-----------------------+------+------------+-----------+
| cfc-worker1  | RUNNING | 192.168.27.101 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-----------------------+------+------------+-----------+
| cfc-worker2  | RUNNING | 192.168.27.102 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-----------------------+------+------------+-----------+

**FROM THE cfc-manager1 log**
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.09.0~ce-0~ubuntu_amd64.deb  GnuTLS recv error (-54): Error in the pull function.

**Comment by tpouyer** [comment]
have you verified that you can reach that URL from the cfc-manager1?

**Comment by bluegoose13** [comment]
I deleted the VM in virtual box and re-ran the script.  I tried this several times and it eventually completed successfully.  I didn't change anything but did close out everything and reboot my Mac.

**Comment by bluegoose13** [comment]
With seeing other's having this issue it would be helpful to have a step to verify you can reach the URL from cfc-manager1.
