### ISSUE TITLE
Error at Build Installer Image task using Ansible SL

### ISSUE THREAD

**Issue by MohammedFadin** [IBM/deploy-ibm-cloud-private#55]
Hi All,

Everything goes fine, until it the installer image build task start on the Master node, I get the below error.

<img width="993" alt="screen shot 2017-11-13 at 11 58 20 pm" src="https://user-images.githubusercontent.com/2106384/32749025-09872596-c8cf-11e7-80fe-93306c3fff0d.png">

**Comment by vmorris** [comment]
Some problem with that `pip install softlayer` step.
It does say `temporary error (try again later)`...

**Comment by MohammedFadin** [comment]
Any solution you suggest? I tried multiple times, same issue.

**Comment by MohammedFadin** [comment]
Okay I'm closing this issue, it seems it was a problem from Softlayer API.
